rootProject.name = 'notification-service'
include(
        "api",
        "application",
        "infrastructure",
        "domain",
        "bootstrap",
        'shared'
)

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
