services:
  api-gateway:
    build:
    image: minhhien6634/studydocs/api-gateway:2026-01-17
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - gateway.env
    environment:
      - SERVER_PORT=8080
    networks:
      - studydocs-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - microservices-network

  # zipkin:
  #   image: openzipkin/zipkin
  #   container_name: zipkin
  #   ports:
  #     - "9411:9411"
  #   networks:
  #     - microservices-network

networks:
  studydocs-network:
    external: true
