FROM eclipse-temurin:17-jdk-alpine AS build
WORKDIR /app
COPY . .

# Cài gradle
RUN apk add --no-cache gradle

RUN gradle clean bootJar -x test


FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY --from=build /app/build/libs/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]
