version: '3.8'

services:
#  api-gateway:
#    build: .
#    image: api-gateway:latest
#    container_name: api-gateway
#    ports:
#      - "8080:8080"
#    env_file:
#      - .env
#    depends_on:
#      - redis
#      - zipkin
#    networks:
#      - microservices-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
#    networks:
#      - microservices-network

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
#    networks:
#      - microservices-network

#networks:
#  microservices-network:
#    external: true
