plugins {
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:3.5.3"
    }
}

dependencies {
    implementation project(':api')
    implementation project(':infrastructure')
    implementation project(':application')
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation("me.paulschwarz:spring-dotenv:4.0.0")
}

