plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'com.github.vanhao'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-security:3.2.1'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server:3.2.1'
    implementation 'org.springframework.boot:spring-boot-starter-web:3.2.1'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.3'
    
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
