version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: auth_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbauthservice
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: 123456789
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  auth-service:
    build: .
    container_name: auth_service
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: dbauthservice
      DB_MYSQL_USERNAME: auth_user
      DB_MYSQL_PASSWORD: 123456789
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"

volumes:
  mysql_data:
