server:
  address: ${SERVER_ADDRESS:0.0.0.0}
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASS}@user.hzlz13a.mongodb.net/${MONGO_DATABASE}?retryWrites=true&w=majority&tls=true&appName=User
      uuid-representation: standard
  security:
    oauth2:
      resourceserver:
        jwt:
          # JWKS endpoint từ auth service
          jwk-set-uri: ${AUTH_SERVICE_JWKS_URL}
          # Issuer từ demo-auth
          issuer-uri: ${AUTH_SERVICE_ISSUER}
notification:
  service:
    url: ${NOTIFICATION_SERVICE_URL:http://notification-service/api/v1/notifications/user-profiles}
upload-file:
  service:
    url: ${UPLOADFILE_SERVICE_URL:http://notification-service/api/v1/notifications/user-profiles}
