server:
  port: 8084

spring:
  application:
    name: media-service
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}
  data:
    mongodb:
      uri: ${MONGODB_URI}
      uuid-representation: standard
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    virtual-host: ${RABBIT_VIRTUAL_HOST}
    ssl:
      enabled: ${RABBIT_SSL}

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

app:
  error:
    code: ${ERROR_CODE}
  outbox:
    schedule:
      fixed-delay: ${SCHEDULE_DELAY}
    batch-size: ${BATCH_SIZE}
