server:
  port: 8084

spring:
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  data:
    mongodb:
      uri: ${MONGODB_URI}
      uuid-representation: standard
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    virtual-host: ${RABBIT_VIRTUAL_HOST}
    ssl:
      enabled: true

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

app:
  error:
    code: ${ERROR_CODE}
  outbox:
    schedule:
      fixed-delay: 5000
    batch-size: 20

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security.oauth2: DEBUG
