plugins {
    id 'org.springframework.boot'
}
dependencies {
    implementation project(":shared")
    implementation project(":domain")
    implementation project(":application")
    //web
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    //env
    implementation("me.paulschwarz:spring-dotenv:4.0.0")
    //mail
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    //mongo
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
    //rabbit
    implementation 'org.springframework.boot:spring-boot-starter-amqp'
    //lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    //test
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:rabbitmq'
    testImplementation 'org.testcontainers:mongodb'
    testImplementation 'org.springframework.amqp:spring-rabbit-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}