server:
  address: ${SERVER_ADDRESS:0.0.0.0}
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: user-service

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://user1:12345@localhost:27017/userDB?authSource=admin}
      uuid-representation: standard

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVICE_JWKS_URL:http://192.168.1.33:8081/api/v1/auth/.well-known/jwks.json}
          issuer-uri: ${AUTH_SERVICE_ISSUER:http://192.168.1.33:8081/api/v1/auth}

notification:
  service:
    url: ${NOTIFICATION_SERVICE_URL:http://notification-service/api/v1/notifications/user-profiles}

media:
  service:
    url: ${MEDIA_SERVICE_URL:http://meida-service/api/v1/assets}