plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.3' apply(false)
    id 'io.spring.dependency-management' version '1.1.7' apply(false)
}

group = 'studydocs.media'
version = '1.0-SNAPSHOT'

ext {
    lombokVersion = '1.18.36'
}

subprojects {
    apply plugin: 'java'
    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
    }
    test {
        useJUnitPlatform()
    }
    configurations {
        compileOnly {
            extendsFrom annotationProcessor
        }
    }
}