version: '3.8'

services:
  media-service:
    build: .
    container_name: media-service
    ports:
      - "8080:8080"
    env_file:
      - .env.docker
    volumes:
      - media_storage:/app/storage
    depends_on:
      - postgres.media.local
      - clamav.media.local
      - redis.media.local

  postgres.media.local:
    image: postgres:15-alpine
    container_name: postgres-media
    environment:
      - POSTGRES_DB=media_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  clamav.media.local:
    image: clamav/clamav:latest # Sử dụng bản ClamAV mới nhất
    container_name: clamav-media
    ports:
      - "3310:3310"
    restart: unless-stopped
    # Mount DB virus ra ngoài giúp lần sau startup nhanh hơn không bị tải lại dữ liệu từ đầu
    volumes:
      - clamav_data:/var/lib/clamav

  redis.media.local:
    image: redis:7-alpine
    container_name: redis-media
    ports:
      - "6379:6379"

volumes:
  pgdata:
  media_storage:
  clamav_data:
