server:
  port: ${SERVER_PORT:8089}
spring:
  application:
    name: FollowerService
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_MYSQL_USERNAME}
    password: ${DB_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    virtual-host: ${RABBIT_VIRTUAL_HOST}
    ssl:
      enabled: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: CHAR

  security:
    oauth2:
      resourceserver:
        jwt:
          # JWKS endpoint từ demo-auth service
          jwk-set-uri: ${AUTH_SERVICE_JWKS_URL:http://localhost:8080/.well-known/jwks.json}
          # Issuer từ demo-auth
          issuer-uri: ${AUTH_SERVICE_ISSUER:http://localhost:8080}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
