server:
  port: 9051

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/reviews
      uuid-representation: standard

document:
  service:
    url: http://localhost:9050/documents

auth:
  server:
#    jwk-set-uri: http://localhost:8081/oauth2/jwks
    issuer: http://localhost:8081

logging:
  level:
    #    org.springframework: DEBUG
    org.springframework.data.mongodb: DEBUG
    #    org.springframework.web: DEBUG
    org.springframework.security: DEBUG