server:
  port: ${SERVER_PORT:9051}

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/reviews  # Database tên 'reviews'
      auto-index-creation: true

document:
  service:
    url: http://localhost:9050/documents  # URL của Document Service

#logging:
#  level:
#    org.springframework: DEBUG
#    org.springframework.data.mongodb: DEBUG
#    org.springframework.web: DEBUG