version: "3.8"

services:
  user-service:
    build: .
    image: user-service:latest
    container_name: user-service
    ports:
      - "8082:8082"
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - microservices-network

  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user1
      MONGO_INITDB_ROOT_PASSWORD: 12345
      MONGO_INITDB_DATABASE: userDB
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true
volumes:
  mongo_data:
