plugins {
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:3.5.3"
    }
}

dependencies {
    implementation project(':domain')
    implementation 'org.springframework.boot:spring-boot-starter'
    compileOnly "org.projectlombok:lombok"
    annotationProcessor "org.projectlombok:lombok"
}
