server:
  port: 8082
spring:
  config:
    name: notification-service
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    virtual-host: ${RABBIT_VIRTUAL_HOST}
    ssl:
      enabled: true
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}
      uuid-representation: standard
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8081
app:
  remote:
    user-service:
      url: ${USER_SERVICE_URL:http://localhost:8082/api/v1/users}
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

