server:
  port: 9050

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/document?useSSL=false&serverTimezone=UTC
    username: sa
    password: 1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 60000
upload:
  service:
    url: http://localhost:9150/api/upload