server:
  port: ${SERVER_PORT:8085}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/document?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false}
    username: ${SPRING_DATASOURCE_USERNAME:studydocs}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: -1

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    repair-on-migrate: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SECURITY_OAUTH2_JWT_ISSUER_URI:http://192.168.1.33:8081}
          jwk-set-uri: ${AUTH_SERVICE_JWKS_URL:http://192.168.1.33:8081/.well-known/jwks.json}

upload:
  service:
    url: ${UPLOAD_SERVICE_URL:http://10.0.0.170:8084/api/v1/files}

notification:
  service:
    url: ${NOTIFICATION_SERVICE_URL:http://10.0.0.170:8087/api/v1/notifications}

academic:
  service:
    url: ${ACADEMIC_SERVICE_URL:http://192.168.1.33:8083/api/v1/academics/documents}

review:
  service:
    url: ${REVIEW_SERVICE_URL:http://localhost:8086}



logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
